### ISSUE TITLE
How to get Shading Object in PDF

### ISSUE THREAD

**Issue by anvy2024** [datalogics/apdfl-csharp-dotnet-samples#57]
I am currently evaluating the Datalogics.PDFL library for a project involving PDF processing. During the process, I encountered an issue when trying to extract shading objects that have already been transformed by transferance in an image.

Could you please advise on the best method to retrieve shading from a PDF object when the shading has already been transformed? 
Thank you in advance for your assistance, and I look forward to your guidance on this matter.

**Comment by datalogics-josepha** [comment]
Please [contact](https://www.datalogics.com/tech-support-pdfs) our Support Department and our team will be happy to be of assistance.
